In [20]:
from google.colab import drive
import pandas as pd
drive.mount('/content/drive')
import os

print(os.listdir("/content/drive/MyDrive"))



df = pd.read_csv(
    "/content/drive/MyDrive/heart_disease_uci.csv"
)

print(df.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
['Colab Notebooks', 'StudentsPerformance.csv', 'test.csv', 'train.csv', 'heart_disease_uci.csv', 'X-VPN_Installer76.4_4386_da4eeb6d_2024-08-15-05-50-58.exe', 'tsetup-x64.5.16.4.exe', 'hotel_bookings.csv', 'BMW sales data (2010-2024) (1).csv', 'Advertising.csv', 'Housing_Data (1).csv', 'EconomiesOfScale.csv', 'iris.csv', 'wine.csv', 'breast-cancer.csv']
   id  age     sex    dataset               cp  trestbps   chol    fbs  \
0   1   63    Male  Cleveland   typical angina     145.0  233.0   True
1   2   67    Male  Cleveland     asymptomatic     160.0  286.0  False
2   3   67    Male  Cleveland     asymptomatic     120.0  229.0  False
3   4   37    Male  Cleveland      non-anginal     130.0  250.0  False
4   5   41  Female  Cleveland  atypical angina     130.0  204.0  False

          restecg  thalch  exang  oldpeak        slope   ca  \
0  lv hypertrophy   150.0  False      2.3  downsloping  0.0
1  lv hypertrophy   108.0   True      1.5         flat  3.0
2  lv hypertrophy   129.0   True      2.6         flat  2.0
3          normal   187.0  False      3.5  downsloping  0.0
4  lv hypertrophy   172.0  False      1.4    upsloping  0.0

                thal  num
0       fixed defect    0
1             normal    2
2  reversable defect    1
3             normal    0
4             normal    0

In [21]:
print(df.head())

print(df.shape)

print(df.info())

print(df.isnull().sum())

   id  age     sex    dataset               cp  trestbps   chol    fbs  \
0   1   63    Male  Cleveland   typical angina     145.0  233.0   True
1   2   67    Male  Cleveland     asymptomatic     160.0  286.0  False
2   3   67    Male  Cleveland     asymptomatic     120.0  229.0  False
3   4   37    Male  Cleveland      non-anginal     130.0  250.0  False
4   5   41  Female  Cleveland  atypical angina     130.0  204.0  False

          restecg  thalch  exang  oldpeak        slope   ca  \
0  lv hypertrophy   150.0  False      2.3  downsloping  0.0
1  lv hypertrophy   108.0   True      1.5         flat  3.0
2  lv hypertrophy   129.0   True      2.6         flat  2.0
3          normal   187.0  False      3.5  downsloping  0.0
4  lv hypertrophy   172.0  False      1.4    upsloping  0.0

                thal  num
0       fixed defect    0
1             normal    2
2  reversable defect    1
3             normal    0
4             normal    0
(920, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        920 non-null    int64
 1   age       920 non-null    int64
 2   sex       920 non-null    object
 3   dataset   920 non-null    object
 4   cp        920 non-null    object
 5   trestbps  861 non-null    float64
 6   chol      890 non-null    float64
 7   fbs       830 non-null    object
 8   restecg   918 non-null    object
 9   thalch    865 non-null    float64
 10  exang     865 non-null    object
 11  oldpeak   858 non-null    float64
 12  slope     611 non-null    object
 13  ca        309 non-null    float64
 14  thal      434 non-null    object
 15  num       920 non-null    int64
dtypes: float64(5), int64(3), object(8)
memory usage: 115.1+ KB
None
id            0
age           0
sex           0
dataset       0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
num           0
dtype: int64

In [22]:
df["num"].value_counts()

num
0    411
1    265
2    109
3    107
4     28
Name: count, dtype: int64

In [24]:
df["target"]=(df["num"]>0).astype(int)
df.corr(numeric_only=True)["num"].sort_values(ascending=False)

num         1.000000
target      0.783387
ca          0.516216
oldpeak     0.443084
age         0.339596
id          0.273552
trestbps    0.122291
chol       -0.231547
thalch     -0.366265
Name: num, dtype: float64

In [27]:
print(df["ca"].value_counts(dropna=False))
print(df["thal"].value_counts(dropna=False))

ca
NaN    611
0.0    181
1.0     67
2.0     41
3.0     20
Name: count, dtype: int64
thal
NaN                  486
normal               196
reversable defect    192
fixed defect          46
Name: count, dtype: int64

In [32]:

print(df.shape)

print(df.isnull().sum())

(920, 14)
age           0
sex           0
dataset       0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
num           0
target        0
dtype: int64

In [33]:
df["slope"].value_counts(dropna=False)

slope
flat           345
NaN            309
upsloping      203
downsloping     63
Name: count, dtype: int64

In [34]:
df["target"].value_counts()

target
1    509
0    411
Name: count, dtype: int64

In [35]:
numeric_cols = [
    "trestbps",
    "chol",
    "thalch",
    "oldpeak"
]

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [36]:
categorical_cols = [
    "fbs",
    "restecg",
    "exang",
    "slope"
]

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

/tmp/ipykernel_1275/4203646300.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(df[col].mode()[0])

In [37]:
print(df.isnull().sum())

age         0
sex         0
dataset     0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalch      0
exang       0
oldpeak     0
slope       0
num         0
target      0
dtype: int64

In [39]:
df = pd.get_dummies(df, drop_first=True)
print(df.shape)
print(df.head())

(920, 20)
   age  trestbps   chol    fbs  thalch  exang  oldpeak  num  target  sex_Male  \
0   63     145.0  233.0   True   150.0  False      2.3    0       0      True
1   67     160.0  286.0  False   108.0   True      1.5    2       1      True
2   67     120.0  229.0  False   129.0   True      2.6    1       1      True
3   37     130.0  250.0  False   187.0  False      3.5    0       0      True
4   41     130.0  204.0  False   172.0  False      1.4    0       0     False

   dataset_Hungary  dataset_Switzerland  dataset_VA Long Beach  \
0            False                False                  False
1            False                False                  False
2            False                False                  False
3            False                False                  False
4            False                False                  False

   cp_atypical angina  cp_non-anginal  cp_typical angina  restecg_normal  \
0               False           False               True           False
1               False           False              False           False
2               False           False              False           False
3               False            True              False            True
4                True           False              False           False

   restecg_st-t abnormality  slope_flat  slope_upsloping
0                     False       False            False
1                     False        True            False
2                     False        True            False
3                     False       False            False
4                     False       False             True

In [45]:
X = df.drop(["num", "target"], axis=1)

y = df["target"]
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=500,
    random_state=42
)

model.fit(X_train, y_train)

print("Model Trained")
y_pred = model.predict(X_test)

Model Trained

In [46]:
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

print("Accuracy:",
      accuracy_score(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy: 0.8586956521739131
[[62 13]
 [13 96]]
              precision    recall  f1-score   support

           0       0.83      0.83      0.83        75
           1       0.88      0.88      0.88       109

    accuracy                           0.86       184
   macro avg       0.85      0.85      0.85       184
weighted avg       0.86      0.86      0.86       184

In [47]:
import joblib

joblib.dump(model, "heart_disease_model.pkl")

['heart_disease_model.pkl']